import { DEFAULT_CACHE_EPOCH } from './cacheEpoch';
import { parseProviderPolicies } from './posterCache/config';

export interface DisabledRule {
  settingKey: string;
  operator: 'eq' | 'neq';
  value: string;
  reason: string;
}

export interface SettingDefinition {
  key: string;
  envVar: string;
  legacyEnvVar?: string;
  label: string;
  description: string;
  category: string;
  type: 'string' | 'number' | 'boolean' | 'select';
  default: string | number | boolean;
  options?: string[];
  sensitive?: boolean;
  requiresRestart?: boolean;
  envOnly?: boolean;
  validate?: (v: string) => boolean;
  disabledWhen?: DisabledRule[];
  uiHint?: 'tags';
  maxTags?: number;
  min?: number;
  max?: number;
}

export const SETTINGS_REGISTRY: SettingDefinition[] = [
  // --- API Keys ---
  {
    key: 'TMDB_API_KEY',
    envVar: 'TMDB_API_KEY',
    legacyEnvVar: 'TMDB_API',
    label: 'TMDB API Key',
    description: 'The Movie Database API key for metadata lookups',
    category: 'API Keys',
    type: 'string',
    default: '',
    sensitive: true,
  },
  {
    key: 'TVDB_API_KEY',
    envVar: 'TVDB_API_KEY',
    label: 'TVDB API Key',
    description: 'TheTVDB API key for TV metadata',
    category: 'API Keys',
    type: 'string',
    default: '',
    sensitive: true,
  },
  {
    key: 'FANART_API_KEY',
    envVar: 'FANART_API_KEY',
    label: 'Fanart.tv API Key',
    description: 'Fanart.tv API key for artwork',
    category: 'API Keys',
    type: 'string',
    default: '',
    sensitive: true,
  },
  {
    key: 'RPDB_API_KEY',
    envVar: 'RPDB_API_KEY',
    label: 'RPDB API Key',
    description: 'Rating Poster Database API key',
    category: 'API Keys',
    type: 'string',
    default: '',
    sensitive: true,
  },
  {
    key: 'MDBLIST_API_KEY',
    envVar: 'MDBLIST_API_KEY',
    label: 'MDBList API Key',
    description: 'MDBList API key for lists and ratings',
    category: 'API Keys',
    type: 'string',
    default: '',
    sensitive: true,
  },
  {
    key: 'GEMINI_API_KEY',
    envVar: 'GEMINI_API_KEY',
    label: 'Gemini API Key',
    description: 'Google Gemini API key for AI features',
    category: 'API Keys',
    type: 'string',
    default: '',
    sensitive: true,
  },
  {
    key: 'BUILT_IN_TMDB_API_KEY',
    envVar: 'BUILT_IN_TMDB_API_KEY',
    label: 'Built-in TMDB Key',
    description: 'Server-side TMDB key used as fallback when users have no personal key',
    category: 'API Keys',
    type: 'string',
    default: '',
    sensitive: true,
  },
  {
    key: 'BUILT_IN_TVDB_API_KEY',
    envVar: 'BUILT_IN_TVDB_API_KEY',
    label: 'Built-in TVDB Key',
    description: 'Server-side TVDB key used as fallback when users have no personal key',
    category: 'API Keys',
    type: 'string',
    default: '',
    sensitive: true,
  },
  {
    key: 'BUILT_IN_FANART_API_KEY',
    envVar: 'BUILT_IN_FANART_API_KEY',
    label: 'Built-in Fanart Key',
    description: 'Server-side Fanart.tv key used as fallback',
    category: 'API Keys',
    type: 'string',
    default: '',
    sensitive: true,
  },
  {
    key: 'BUILT_IN_RPDB_API_KEY',
    envVar: 'BUILT_IN_RPDB_API_KEY',
    label: 'Built-in RPDB Key',
    description: 'Server-side RPDB key used as fallback',
    category: 'API Keys',
    type: 'string',
    default: '',
    sensitive: true,
  },

  // --- OAuth (env-only) ---
  {
    key: 'TRAKT_CLIENT_ID',
    envVar: 'TRAKT_CLIENT_ID',
    label: 'Trakt Client ID',
    description: 'Trakt OAuth application client ID. Changing invalidates all user tokens.',
    category: 'OAuth',
    type: 'string',
    default: '',
    sensitive: true,
    envOnly: true,
  },
  {
    key: 'TRAKT_CLIENT_SECRET',
    envVar: 'TRAKT_CLIENT_SECRET',
    label: 'Trakt Client Secret',
    description: 'Trakt OAuth application client secret',
    category: 'OAuth',
    type: 'string',
    default: '',
    sensitive: true,
    envOnly: true,
  },
  {
    key: 'TRAKT_REDIRECT_URI',
    envVar: 'TRAKT_REDIRECT_URI',
    label: 'Trakt Redirect URI',
    description: 'Trakt OAuth redirect URI override',
    category: 'OAuth',
    type: 'string',
    default: '',
    envOnly: true,
  },
  {
    key: 'SIMKL_CLIENT_ID',
    envVar: 'SIMKL_CLIENT_ID',
    label: 'Simkl Client ID',
    description: 'Simkl OAuth application client ID. Changing invalidates all user tokens.',
    category: 'OAuth',
    type: 'string',
    default: '',
    sensitive: true,
    envOnly: true,
  },
  {
    key: 'SIMKL_CLIENT_SECRET',
    envVar: 'SIMKL_CLIENT_SECRET',
    label: 'Simkl Client Secret',
    description: 'Simkl OAuth application client secret',
    category: 'OAuth',
    type: 'string',
    default: '',
    sensitive: true,
    envOnly: true,
  },
  {
    key: 'SIMKL_REDIRECT_URI',
    envVar: 'SIMKL_REDIRECT_URI',
    label: 'Simkl Redirect URI',
    description: 'Simkl OAuth redirect URI override',
    category: 'OAuth',
    type: 'string',
    default: '',
    envOnly: true,
  },
  {
    key: 'ANILIST_CLIENT_ID',
    envVar: 'ANILIST_CLIENT_ID',
    label: 'AniList Client ID',
    description: 'AniList OAuth application client ID. Changing invalidates all user tokens.',
    category: 'OAuth',
    type: 'string',
    default: '',
    sensitive: true,
    envOnly: true,
  },
  {
    key: 'ANILIST_CLIENT_SECRET',
    envVar: 'ANILIST_CLIENT_SECRET',
    label: 'AniList Client Secret',
    description: 'AniList OAuth application client secret',
    category: 'OAuth',
    type: 'string',
    default: '',
    sensitive: true,
    envOnly: true,
  },
  {
    key: 'ANILIST_REDIRECT_URI',
    envVar: 'ANILIST_REDIRECT_URI',
    label: 'AniList Redirect URI',
    description: 'AniList OAuth redirect URI override',
    category: 'OAuth',
    type: 'string',
    default: '',
    envOnly: true,
  },
  {
    key: 'MAL_CLIENT_ID',
    envVar: 'MAL_CLIENT_ID',
    label: 'MyAnimeList Client ID',
    description: 'MyAnimeList OAuth application client ID. Changing invalidates all user tokens.',
    category: 'OAuth',
    type: 'string',
    default: '',
    sensitive: true,
    envOnly: true,
  },
  {
    key: 'MAL_CLIENT_SECRET',
    envVar: 'MAL_CLIENT_SECRET',
    label: 'MyAnimeList Client Secret',
    description: 'MyAnimeList OAuth application client secret',
    category: 'OAuth',
    type: 'string',
    default: '',
    sensitive: true,
    envOnly: true,
  },
  {
    key: 'MAL_REDIRECT_URI',
    envVar: 'MAL_REDIRECT_URI',
    label: 'MyAnimeList Redirect URI',
    description: 'MyAnimeList OAuth redirect URI override',
    category: 'OAuth',
    type: 'string',
    default: '',
    envOnly: true,
  },

  // --- Cache ---
  {
    key: 'META_TTL',
    envVar: 'META_TTL',
    label: 'Meta Cache TTL',
    description: 'Time-to-live for metadata cache entries in seconds',
    category: 'Cache',
    type: 'number',
    default: 604800,
  },
  {
    key: 'CATALOG_TTL',
    envVar: 'CATALOG_TTL',
    label: 'Catalog Cache TTL',
    description: 'Time-to-live for catalog cache entries in seconds',
    category: 'Cache',
    type: 'number',
    default: 86400,
  },
  {
    key: 'ANILIST_CATALOG_TTL',
    envVar: 'ANILIST_CATALOG_TTL',
    label: 'AniList Catalog TTL',
    description: 'Time-to-live for AniList catalog entries in seconds',
    category: 'Cache',
    type: 'number',
    default: 86400,
  },
  {
    key: 'TMDB_TRENDING_TTL',
    envVar: 'TMDB_TRENDING_TTL',
    label: 'TMDB Trending TTL',
    description: 'Time-to-live for TMDB trending cache in seconds',
    category: 'Cache',
    type: 'number',
    default: 10800,
  },
  {
    key: 'CONFIG_CACHE_TTL_SEC',
    envVar: 'CONFIG_CACHE_TTL_SEC',
    label: 'Config Cache TTL',
    description: 'Time-to-live for user config cache in seconds',
    category: 'Cache',
    type: 'number',
    default: 300,
  },
  {
    key: 'CONFIG_CACHE_COMPRESSION_ENABLED',
    envVar: 'CONFIG_CACHE_COMPRESSION_ENABLED',
    label: 'Config Cache Compression',
    description: 'Enable lz4 compression for user config cache entries in Redis',
    category: 'Cache',
    type: 'boolean',
    default: true,
  },
  {
    key: 'CACHE_COMPRESSION_ENABLED',
    envVar: 'CACHE_COMPRESSION_ENABLED',
    label: 'Cache Compression',
    description: 'Enable gzip compression for cached data',
    category: 'Cache',
    type: 'boolean',
    default: false,
  },
  {
    key: 'CACHE_COMPRESSION_MIN_BYTES',
    envVar: 'CACHE_COMPRESSION_MIN_BYTES',
    label: 'Compression Min Bytes',
    description: 'Minimum payload size in bytes before compression is applied',
    category: 'Cache',
    type: 'number',
    default: 1024,
  },
  {
    key: 'CACHE_MAX_RETRIES',
    envVar: 'CACHE_MAX_RETRIES',
    label: 'Cache Max Retries',
    description: 'Max retries for cache read/write operations',
    category: 'Cache',
    type: 'number',
    default: 3,
  },

  // --- Features ---
  {
    key: 'DISABLE_TRAKT_SEARCH',
    envVar: 'DISABLE_TRAKT_SEARCH',
    label: 'Disable Trakt Search',
    description: 'Disable Trakt as a search provider',
    category: 'Features',
    type: 'boolean',
    default: false,
  },
  {
    key: 'DISABLE_SIMKL_SEARCH',
    envVar: 'DISABLE_SIMKL_SEARCH',
    label: 'Disable Simkl Search',
    description: 'On by default. Simkl search runs against a shared client id, so an instance serving many people can spend the allowance for everyone. Turn this off to offer Simkl as a search provider; existing configs that already name it fall back to the default provider until you do.',
    category: 'Features',
    type: 'boolean',
    default: true,
  },
  {
    key: 'DISABLE_METRICS',
    envVar: 'DISABLE_METRICS',
    label: 'Disable Metrics',
    description: 'Disable request tracking and analytics',
    category: 'Features',
    type: 'boolean',
    default: false,
  },
  {
    key: 'DISABLE_GUEST_MODE',
    envVar: 'DISABLE_GUEST_MODE',
    label: 'Disable Guest Mode',
    description: 'Disable guest access to the dashboard',
    category: 'Features',
    type: 'boolean',
    default: false,
  },
  {
    key: 'USER_ALIASES_ENABLED',
    envVar: 'USER_ALIASES_ENABLED',
    label: 'User Aliases',
    description: 'Allow a human-readable alias to be used anywhere a user UUID is accepted, including manifest URLs and configure-page login. Aliases are guessable, so leave this off on public instances.',
    category: 'Features',
    type: 'boolean',
    default: false,
  },
  {
    key: 'USER_ALIASES',
    envVar: 'USER_ALIASES',
    label: 'Seeded User Aliases',
    description: 'Comma-separated alias=uuid pairs applied at startup, e.g. "Cedya=3f8b2c1a-...,mum=11111111-...". Entries here overwrite any alias set from the dashboard on every boot.',
    category: 'Features',
    type: 'string',
    default: '',
    requiresRestart: true,
  },
  {
    key: 'USER_ALIAS_REFRESH_SEC',
    envVar: 'USER_ALIAS_REFRESH_SEC',
    label: 'Alias Cache Refresh',
    description: 'How often the in-memory alias map is refreshed from the database, in seconds. Only matters when running more than one replica.',
    category: 'Features',
    type: 'number',
    default: 30,
  },
  {
    key: 'CUSTOM_DESCRIPTION_BLURB',
    envVar: 'CUSTOM_DESCRIPTION_BLURB',
    label: 'Custom Description Blurb',
    description: 'Custom text appended to the addon description',
    category: 'Features',
    type: 'string',
    default: '',
  },
  {
    key: 'ADDON_NAME_SUFFIX',
    envVar: 'ADDON_NAME_SUFFIX',
    label: 'Addon Name Suffix',
    description: 'Custom suffix appended to the addon name in Stremio',
    category: 'Features',
    type: 'string',
    default: '',
  },
  {
    key: 'ADDON_LOGO_URL',
    envVar: 'ADDON_LOGO_URL',
    label: 'Addon Logo URL',
    description: 'Custom logo URL for the addon in Stremio',
    category: 'Features',
    type: 'string',
    default: '',
  },
  {
    key: 'POSTER_PROXY_PREFIX_URL',
    envVar: 'POSTER_PROXY_PREFIX_URL',
    label: 'Poster Proxy URL',
    description: 'Public URL images are served through. Leave empty with the built-in cache — it derives {HOST_NAME}/poster-cache automatically. Set it only for an external caching proxy.',
    category: 'Features',
    type: 'string',
    default: '',
  },
  {
    key: 'MAX_CATALOGS',
    envVar: 'MAX_CATALOGS',
    label: 'Max Catalogs',
    description: 'Maximum number of catalogs a user can configure (empty = no limit)',
    category: 'Features',
    type: 'number',
    default: '',
  },
  {
    key: 'OIDC_ENABLED',
    envVar: 'OIDC_ENABLED',
    label: 'Enable SSO',
    description: 'Allow signing in with an OpenID Connect provider. Needs an issuer, client id and client secret before it does anything.',
    category: 'Server',
    type: 'boolean',
    default: false,
  },
  {
    key: 'OIDC_ISSUER',
    envVar: 'OIDC_ISSUER',
    label: 'SSO Issuer URL',
    description: "Your provider's root URL, such as https://auth.example.com. Discovery is read from /.well-known/openid-configuration under it.",
    category: 'Server',
    type: 'string',
    default: '',
  },
  {
    key: 'OIDC_CLIENT_ID',
    envVar: 'OIDC_CLIENT_ID',
    label: 'SSO Client ID',
    description: 'The client id your provider issued when you registered this addon.',
    category: 'Server',
    type: 'string',
    default: '',
  },
  {
    key: 'OIDC_CLIENT_SECRET',
    envVar: 'OIDC_CLIENT_SECRET',
    label: 'SSO Client Secret',
    description: 'The client secret your provider issued. Set through the environment only.',
    category: 'Server',
    type: 'string',
    default: '',
    sensitive: true,
    envOnly: true,
  },
  {
    key: 'OIDC_GROUPS_CLAIM',
    envVar: 'OIDC_GROUPS_CLAIM',
    label: 'SSO Groups Claim',
    description: 'Which claim the permission mapping reads. Usually groups. Nothing requires it to be group membership: point it at email and the mapping becomes an allowlist of addresses, which is how providers without groups, such as Google, are handled.',
    category: 'Server',
    type: 'string',
    default: 'groups',
  },
  {
    key: 'OIDC_USERNAME_CLAIM',
    envVar: 'OIDC_USERNAME_CLAIM',
    label: 'SSO Username Claim',
    description: 'Which claim names the account. Empty uses preferred_username, then name, then the email address.',
    category: 'Server',
    type: 'string',
    default: '',
  },
  {
    key: 'OIDC_GROUP_PERMISSIONS',
    envVar: 'OIDC_GROUP_PERMISSIONS',
    label: 'SSO Group Permissions',
    description: 'Maps groups to what they may do, as group=permission|permission separated by commas. Permissions are admin and createConfig; none signs in with neither. A group that is not listed grants nothing, and an unreadable entry refuses the login.',
    category: 'Server',
    type: 'string',
    default: '',
  },
  {
    key: 'OIDC_DEFAULT_PERMISSIONS',
    envVar: 'OIDC_DEFAULT_PERMISSIONS',
    label: 'SSO Default Permissions',
    description: 'What an identity gets when it matches nothing in the mapping. Empty refuses the login, which is what makes an unmatched identity refused rather than admitted. Setting this to admin makes every identity your provider will authenticate an administrator here, which is only safe when the provider itself decides who may reach this instance: true of a private Authelia or Keycloak, not of Google.',
    category: 'Server',
    type: 'string',
    default: '',
  },
  {
    key: 'AUTH_REQUIRE_SIGNIN',
    envVar: 'AUTH_REQUIRE_SIGNIN',
    label: 'Require Sign-In For The Config Page',
    description: 'Makes the configuration and dashboard pages ask for a sign-in before they render, rather than only when saving. Addon routes are untouched: manifests, catalogs, meta, streams and art are still served to clients, which carry no session. Ignored while no identity provider is configured, so turning it on cannot lock you out of an instance that has no way to sign in.',
    category: 'Server',
    type: 'boolean',
    default: 'false',
  },
  {
    key: 'OIDC_ALLOW_INSECURE_ISSUER',
    envVar: 'OIDC_ALLOW_INSECURE_ISSUER',
    label: 'Allow Insecure SSO Issuer',
    description: 'Permit an http issuer. The client secret and tokens then travel in the clear, so this is only for a provider on a trusted network.',
    category: 'Server',
    type: 'boolean',
    default: false,
  },
  {
    key: 'OIDC_RATE_LIMIT_PER_WINDOW',
    envVar: 'OIDC_RATE_LIMIT_PER_WINDOW',
    label: 'SSO Attempts Per Window',
    description: 'How many sign-in attempts one address may make per window. Sign-in creates an account, so this guards an unauthenticated write path.',
    category: 'Server',
    type: 'number',
    default: 20,
  },
  {
    key: 'OIDC_RATE_LIMIT_WINDOW',
    envVar: 'OIDC_RATE_LIMIT_WINDOW',
    label: 'SSO Rate Limit Window (sec)',
    description: 'Length of the sign-in rate limit window.',
    category: 'Server',
    type: 'number',
    default: 300,
  },
  {
    key: 'AUTH_SIGNIN_FAILURE_LOG_MAX',
    envVar: 'AUTH_SIGNIN_FAILURE_LOG_MAX',
    label: 'Sign-in Failures Kept',
    description: 'How many recent refused sign-ins the Accounts tab keeps, so a misconfigured claim can be seen rather than guessed at.',
    category: 'Server',
    type: 'number',
    default: 50,
    min: 1,
    max: 500,
  },
  {
    key: 'AUTH_SIGNIN_FAILURE_LOG_TTL',
    envVar: 'AUTH_SIGNIN_FAILURE_LOG_TTL',
    label: 'Sign-in Failure Retention (sec)',
    description: 'How long a recorded sign-in failure is kept before it expires.',
    category: 'Server',
    type: 'number',
    default: 604800,
  },
  {
    key: 'SESSION_TTL_SECONDS',
    envVar: 'SESSION_TTL_SECONDS',
    label: 'Session Lifetime (sec)',
    description: 'How long a sign-in lasts before it has to be repeated. Group changes at the provider take effect on the next sign-in.',
    category: 'Server',
    type: 'number',
    default: 86400,
  },
  {
    key: 'TRUST_PROXY_HOPS',
    envVar: 'TRUST_PROXY_HOPS',
    label: 'Trusted Proxy Hops',
    description: 'How many reverse proxies sit in front of the addon. Sign-in is rate limited per client address, read that many entries back from the end of X-Forwarded-For. The default of 1 suits a single proxy; raise it if more sit in front, and set 0 if the addon is reachable directly, which reads the address from the socket instead. Set through the environment only.',
    category: 'Server',
    type: 'number',
    default: 1,
    envOnly: true,
  },
  {
    key: 'COLLECTION_IMPORT_CATALOG_CAP',
    envVar: 'COLLECTION_IMPORT_CATALOG_CAP',
    label: 'Collection Import Catalog Cap',
    description: 'Most catalogs a collection import may add, used when Max Catalogs is empty. Community collection files can reference thousands, and every one added becomes a manifest entry.',
    category: 'Features',
    type: 'number',
    default: 300,
  },
  {
    key: 'CATALOG_LIST_ITEMS_SIZE',
    envVar: 'CATALOG_LIST_ITEMS_SIZE',
    label: 'Catalog List Page Size',
    description: 'Number of items per catalog page',
    category: 'Features',
    type: 'number',
    default: 20,
  },
  {
    key: 'ENABLE_SELF_HEALING',
    envVar: 'ENABLE_SELF_HEALING',
    label: 'Self-Healing Cache',
    description: 'Automatically repair corrupted cache entries',
    category: 'Features',
    type: 'boolean',
    default: false,
    requiresRestart: true,
  },

  // --- Essential Warming ---
  {
    key: 'ENABLE_CACHE_WARMING',
    envVar: 'ENABLE_CACHE_WARMING',
    label: 'Enable Cache Warming',
    description: 'Enable automatic background essential cache warming',
    category: 'Essential Warming',
    type: 'boolean',
    default: true,
    requiresRestart: true,
  },
  {
    key: 'CACHE_WARMING_INTERVAL',
    envVar: 'CACHE_WARMING_INTERVAL',
    label: 'Warming Interval (min)',
    description: 'Minutes between essential cache warming runs',
    category: 'Essential Warming',
    type: 'number',
    default: 720,
    requiresRestart: true,
  },
  {
    key: 'CACHE_WARM_INTERVAL_HOURS',
    envVar: 'CACHE_WARM_INTERVAL_HOURS',
    label: 'Popular Warming Interval (hrs)',
    description: 'Hours between popular content warming runs',
    category: 'Essential Warming',
    type: 'number',
    default: 24,
    min: 12,
    validate: (v: string) => parseInt(v, 10) >= 12,
    requiresRestart: true,
  },
  {
    key: 'CACHE_WARM_LANGUAGE',
    envVar: 'CACHE_WARM_LANGUAGE',
    label: 'Warming Language',
    description: 'Language code for cache warming content (e.g. en-US)',
    category: 'Essential Warming',
    type: 'string',
    default: 'en-US',
  },
  {
    key: 'TMDB_POPULAR_WARMING_ENABLED',
    envVar: 'TMDB_POPULAR_WARMING_ENABLED',
    label: 'TMDB Popular Warming',
    description: 'Enable TMDB popular content warming',
    category: 'Essential Warming',
    type: 'boolean',
    default: true,
  },

  // --- Comprehensive Warming ---
  {
    key: 'CACHE_WARMUP_MODE',
    envVar: 'CACHE_WARMUP_MODE',
    label: 'Warmup Mode',
    description: 'Cache warmup mode: essential (default) or comprehensive',
    category: 'Comprehensive Warming',
    type: 'select',
    default: 'essential',
    options: ['essential', 'comprehensive'],
  },
  {
    key: 'CACHE_WARMUP_UUIDS',
    envVar: 'CACHE_WARMUP_UUIDS',
    label: 'Warmup UUIDs',
    description: 'Comma-separated UUIDs to warm catalogs for in comprehensive mode (max 5)',
    category: 'Comprehensive Warming',
    type: 'string',
    default: '',
    uiHint: 'tags',
    maxTags: 5,
    validate: (v: string) => v.split(',').filter(s => s.trim()).length <= 5,
  },
  {
    key: 'CATALOG_WARMUP_INTERVAL_HOURS',
    envVar: 'CATALOG_WARMUP_INTERVAL_HOURS',
    label: 'Warmup Interval (hrs)',
    description: 'Hours between comprehensive warming runs (supports fractional like 0.5)',
    category: 'Comprehensive Warming',
    type: 'number',
    default: 24,
    min: 12,
    validate: (v: string) => parseFloat(v) >= 12,
  },
  {
    key: 'CATALOG_WARMUP_INITIAL_DELAY_SECONDS',
    envVar: 'CATALOG_WARMUP_INITIAL_DELAY_SECONDS',
    label: 'Initial Delay (sec)',
    description: 'Seconds to wait after startup before first comprehensive warming run',
    category: 'Comprehensive Warming',
    type: 'number',
    default: 300,
  },
  {
    key: 'CATALOG_WARMUP_MAX_PAGES_PER_CATALOG',
    envVar: 'CATALOG_WARMUP_MAX_PAGES_PER_CATALOG',
    label: 'Max Pages Per Catalog',
    description: 'Maximum pages to warm per catalog',
    category: 'Comprehensive Warming',
    type: 'number',
    default: 100,
  },
  {
    key: 'CATALOG_WARMUP_TASK_DELAY_MS',
    envVar: 'CATALOG_WARMUP_TASK_DELAY_MS',
    label: 'Task Delay (ms)',
    description: 'Delay between individual warming tasks to avoid rate limiting',
    category: 'Comprehensive Warming',
    type: 'number',
    default: 100,
  },
  {
    key: 'CATALOG_WARMUP_RESUME_ON_RESTART',
    envVar: 'CATALOG_WARMUP_RESUME_ON_RESTART',
    label: 'Resume on Restart',
    description: 'Resume warming progress after container restart',
    category: 'Comprehensive Warming',
    type: 'boolean',
    default: true,
  },
  {
    key: 'CATALOG_WARMUP_QUIET_HOURS_ENABLED',
    envVar: 'CATALOG_WARMUP_QUIET_HOURS_ENABLED',
    label: 'Quiet Hours Enabled',
    description: 'Pause warming during quiet hours',
    category: 'Comprehensive Warming',
    type: 'boolean',
    default: false,
  },
  {
    key: 'CATALOG_WARMUP_QUIET_HOURS',
    envVar: 'CATALOG_WARMUP_QUIET_HOURS',
    label: 'Quiet Hours Range',
    description: 'Time range for quiet hours (e.g. 02:00-06:00)',
    category: 'Comprehensive Warming',
    type: 'string',
    default: '02:00-06:00',
  },
  {
    key: 'CATALOG_WARMUP_LOG_LEVEL',
    envVar: 'CATALOG_WARMUP_LOG_LEVEL',
    label: 'Log Level',
    description: 'Log verbosity for comprehensive warming',
    category: 'Comprehensive Warming',
    type: 'select',
    default: 'info',
    options: ['debug', 'info', 'warn', 'error'],
  },
  {
    key: 'CATALOG_WARMUP_AUTO_ON_EPOCH_CHANGE',
    envVar: 'CATALOG_WARMUP_AUTO_ON_EPOCH_CHANGE',
    legacyEnvVar: 'CATALOG_WARMUP_AUTO_ON_VERSION_CHANGE',
    label: 'Auto on Cache Epoch Change',
    description: 'Trigger comprehensive warming when CACHE_EPOCH is bumped, which is what supersedes every cached key. Previously keyed off the addon version, back when keys carried it; a release alone no longer invalidates anything, so warming on it only repeated work.',
    category: 'Comprehensive Warming',
    type: 'boolean',
    default: false,
  },
  {
    key: 'POSTER_WARMUP_URL',
    envVar: 'POSTER_WARMUP_URL',
    label: 'Poster Warmup URL',
    description: 'Base URL for poster warming requests',
    category: 'Comprehensive Warming',
    type: 'string',
    default: '',
  },

  // --- MAL Warming ---
  {
    key: 'MAL_WARMUP_ENABLED',
    envVar: 'MAL_WARMUP_ENABLED',
    label: 'MAL Warmup Enabled',
    description: 'Enable MyAnimeList catalog warming',
    category: 'MAL Warming',
    type: 'boolean',
    default: false,
  },
  {
    key: 'MAL_WARMUP_INTERVAL_HOURS',
    envVar: 'MAL_WARMUP_INTERVAL_HOURS',
    label: 'MAL Warmup Interval (hrs)',
    description: 'Hours between MAL warming runs',
    category: 'MAL Warming',
    type: 'number',
    default: 24,
  },
  {
    key: 'MAL_WARMUP_INITIAL_DELAY_SECONDS',
    envVar: 'MAL_WARMUP_INITIAL_DELAY_SECONDS',
    label: 'MAL Initial Delay (sec)',
    description: 'Seconds to wait after startup before MAL warming',
    category: 'MAL Warming',
    type: 'number',
    default: 300,
  },
  {
    key: 'MAL_WARMUP_TASK_DELAY_MS',
    envVar: 'MAL_WARMUP_TASK_DELAY_MS',
    label: 'MAL Task Delay (ms)',
    description: 'Delay between MAL warming requests',
    category: 'MAL Warming',
    type: 'number',
    default: 100,
  },
  {
    key: 'MAL_WARMUP_DECADES',
    envVar: 'MAL_WARMUP_DECADES',
    label: 'MAL Warmup Decades',
    description: 'Comma-separated decades to warm (e.g. 2020s,2010s)',
    category: 'MAL Warming',
    type: 'string',
    default: '',
    uiHint: 'tags',
  },
  {
    key: 'MAL_WARMUP_PRIORITY_PAGES',
    envVar: 'MAL_WARMUP_PRIORITY_PAGES',
    label: 'MAL Priority Pages',
    description: 'Number of pages to fetch for priority genres',
    category: 'MAL Warming',
    type: 'number',
    default: 3,
  },
  {
    key: 'MAL_WARMUP_LOG_LEVEL',
    envVar: 'MAL_WARMUP_LOG_LEVEL',
    label: 'MAL Log Level',
    description: 'Log verbosity for MAL warming',
    category: 'MAL Warming',
    type: 'select',
    default: 'info',
    options: ['debug', 'info', 'warn', 'error'],
  },
  {
    key: 'MAL_WARMUP_QUIET_HOURS_ENABLED',
    envVar: 'MAL_WARMUP_QUIET_HOURS_ENABLED',
    label: 'MAL Quiet Hours',
    description: 'Pause MAL warming during quiet hours',
    category: 'MAL Warming',
    type: 'boolean',
    default: false,
  },
  {
    key: 'MAL_WARMUP_QUIET_HOURS_RANGE',
    envVar: 'MAL_WARMUP_QUIET_HOURS_RANGE',
    label: 'MAL Quiet Hours Range',
    description: 'Time range for MAL quiet hours',
    category: 'MAL Warming',
    type: 'string',
    default: '02:00-06:00',
  },

  // --- Rate Limiting ---
  {
    key: 'POSTER_PROXY_TIMEOUT_MS',
    envVar: 'POSTER_PROXY_TIMEOUT_MS',
    label: 'Poster Proxy Timeout (ms)',
    description: 'Milliseconds to wait for an upstream poster/art image before serving the fallback. Raise this if a slow rating/poster-generation service times out on first render.',
    category: 'Rate Limiting',
    type: 'number',
    default: 10000,
  },
  {
    key: 'CONFIG_LOAD_RATE_LIMIT_PER_MIN',
    envVar: 'CONFIG_LOAD_RATE_LIMIT_PER_MIN',
    label: 'Config Load Rate Limit',
    description: 'Maximum configure-page login attempts per account per minute. Matters most when user aliases are enabled, since aliases are guessable.',
    category: 'Rate Limiting',
    type: 'number',
    default: 20,
  },
  {
    key: 'JIKAN_MAX_CONCURRENT',
    envVar: 'JIKAN_MAX_CONCURRENT',
    label: 'Jikan Max Concurrent',
    description: 'Maximum concurrent requests to Jikan API',
    category: 'Rate Limiting',
    type: 'number',
    default: 3,
    requiresRestart: true,
  },
  {
    key: 'JIKAN_MAX_PER_MINUTE',
    envVar: 'JIKAN_MAX_PER_MINUTE',
    label: 'Jikan Max Per Minute',
    description: 'Maximum requests per minute to Jikan API',
    category: 'Rate Limiting',
    type: 'number',
    default: 60,
    requiresRestart: true,
  },
  {
    key: 'JIKAN_MIN_INTERVAL',
    envVar: 'JIKAN_MIN_INTERVAL',
    label: 'Jikan Min Interval (ms)',
    description: 'Minimum milliseconds between Jikan requests',
    category: 'Rate Limiting',
    type: 'number',
    default: 334,
    requiresRestart: true,
  },
  {
    key: 'JIKAN_EPISODE_PAGE_TTL',
    envVar: 'JIKAN_EPISODE_PAGE_TTL',
    label: 'Jikan Episode Page TTL (seconds)',
    description: 'How long a settled episode page is cached. MAL pages episodes at 100 and only the newest page gains any, so the pages behind it rarely change.',
    category: 'Rate Limiting',
    type: 'number',
    default: 7 * 24 * 60 * 60,
  },
  {
    key: 'JIKAN_EPISODE_LATEST_PAGE_TTL',
    envVar: 'JIKAN_EPISODE_LATEST_PAGE_TTL',
    label: 'Jikan Latest Episode Page TTL (seconds)',
    description: 'How long the newest episode page is cached. New episodes land here, and a short scrape ages out on this timer. Raise it on a rate-limited Jikan.',
    category: 'Rate Limiting',
    type: 'number',
    default: 6 * 60 * 60,
  },
  {
    key: 'JIKAN_API_BASE',
    envVar: 'JIKAN_API_BASE',
    label: 'Jikan API Base URL',
    description: 'Base URL for Jikan API (self-hosted or default)',
    category: 'Rate Limiting',
    type: 'string',
    default: 'https://api.jikan.moe/v4',
  },
  {
    key: 'TEST_KEYS_RATE_LIMIT_PER_MIN',
    envVar: 'TEST_KEYS_RATE_LIMIT_PER_MIN',
    label: 'Key Test Rate Limit',
    description: 'Max API key test requests per minute',
    category: 'Rate Limiting',
    type: 'number',
    default: 60,
  },
  {
    key: 'SIMKL_TRENDING_PAGE_SIZE_OPTIONS',
    envVar: 'SIMKL_TRENDING_PAGE_SIZE_OPTIONS',
    label: 'Simkl Trending Page Sizes',
    description: 'Comma-separated page size options for Simkl trending',
    category: 'Rate Limiting',
    type: 'string',
    default: '50,100',
    uiHint: 'tags',
  },

  // --- Data Updates ---
  {
    key: 'IMDB_RATINGS_UPDATE_INTERVAL_HOURS',
    envVar: 'IMDB_RATINGS_UPDATE_INTERVAL_HOURS',
    label: 'IMDb Ratings Update (hrs)',
    description: 'Hours between IMDb ratings dataset updates',
    category: 'Data Updates',
    type: 'number',
    default: 24,
    requiresRestart: true,
  },
  {
    key: 'ANIME_LIST_UPDATE_INTERVAL_HOURS',
    envVar: 'ANIME_LIST_UPDATE_INTERVAL_HOURS',
    label: 'Anime List Update (hrs)',
    description: 'Hours between anime list mapping updates',
    category: 'Data Updates',
    type: 'number',
    default: 168,
    requiresRestart: true,
  },
  {
    key: 'ANIME_API_OVERLAY_ENABLED',
    envVar: 'ANIME_API_OVERLAY_ENABLED',
    label: 'animeApi Overlay',
    description: 'Backfill the anime ids the anime list no longer receives (MAL, AniList, Kitsu, Simkl) from animeApi',
    category: 'Data Updates',
    type: 'boolean',
    default: true,
    requiresRestart: true,
  },
  {
    key: 'WIKI_MAPPER_UPDATE_INTERVAL_HOURS',
    envVar: 'WIKI_MAPPER_UPDATE_INTERVAL_HOURS',
    label: 'Wiki Mapper Update (hrs)',
    description: 'Hours between wiki mapper data updates',
    category: 'Data Updates',
    type: 'number',
    default: 168,
    requiresRestart: true,
  },
  {
    key: 'KITSU_TO_IMDB_UPDATE_INTERVAL_HOURS',
    envVar: 'KITSU_TO_IMDB_UPDATE_INTERVAL_HOURS',
    label: 'Kitsu-IMDb Update (hrs)',
    description: 'Hours between Kitsu to IMDb mapping updates',
    category: 'Data Updates',
    type: 'number',
    default: 168,
    requiresRestart: true,
  },
  {
    key: 'TRAKT_ANIME_MOVIES_UPDATE_INTERVAL_HOURS',
    envVar: 'TRAKT_ANIME_MOVIES_UPDATE_INTERVAL_HOURS',
    label: 'Trakt Anime Movies Update (hrs)',
    description: 'Hours between Trakt anime movies list updates',
    category: 'Data Updates',
    type: 'number',
    default: 168,
    requiresRestart: true,
  },

  // --- Proxy ---
  {
    key: 'HTTP_PROXY',
    envVar: 'HTTP_PROXY',
    label: 'HTTP Proxy',
    description: 'HTTP proxy URL for outgoing requests',
    category: 'Proxy',
    type: 'string',
    default: '',
    requiresRestart: true,
  },
  {
    key: 'HTTPS_PROXY',
    envVar: 'HTTPS_PROXY',
    label: 'HTTPS Proxy',
    description: 'HTTPS proxy URL for outgoing requests',
    category: 'Proxy',
    type: 'string',
    default: '',
    requiresRestart: true,
  },
  {
    key: 'TMDB_SOCKS_PROXY_URL',
    envVar: 'TMDB_SOCKS_PROXY_URL',
    label: 'TMDB SOCKS Proxy',
    description: 'SOCKS proxy URL specifically for TMDB requests',
    category: 'Proxy',
    type: 'string',
    default: '',
    requiresRestart: true,
  },
  {
    key: 'MAL_SOCKS_PROXY_URL',
    envVar: 'MAL_SOCKS_PROXY_URL',
    label: 'MAL SOCKS Proxy',
    description: 'SOCKS proxy URL specifically for MAL/Jikan requests',
    category: 'Proxy',
    type: 'string',
    default: '',
    requiresRestart: true,
  },

  // --- Diagnostics ---
  {
    key: 'LOG_BUFFER_SIZE',
    envVar: 'LOG_BUFFER_SIZE',
    label: 'Log Buffer Size',
    description: 'Maximum number of log entries kept in memory',
    category: 'Diagnostics',
    type: 'number',
    default: 100000,
    requiresRestart: true,
  },
  {
    key: 'CACHE_HEALTH_CHECK_INTERVAL',
    envVar: 'CACHE_HEALTH_CHECK_INTERVAL',
    label: 'Cache Health Check (sec)',
    description: 'Seconds between cache health check runs',
    category: 'Diagnostics',
    type: 'number',
    default: 300,
  },
  {
    key: 'CACHE_CORRUPTED_THRESHOLD',
    envVar: 'CACHE_CORRUPTED_THRESHOLD',
    label: 'Corrupted Cache Threshold',
    description: 'Number of corrupted entries before triggering self-healing',
    category: 'Diagnostics',
    type: 'number',
    default: 10,
  },
  {
    key: 'MAX_TRACKED_KEYS',
    envVar: 'MAX_TRACKED_KEYS',
    label: 'Max Tracked Keys',
    description: 'Maximum number of cache keys to track for analytics',
    category: 'Diagnostics',
    type: 'number',
    default: 10000,
  },
  {
    key: 'DASHBOARD_METADATA_LANGUAGE',
    envVar: 'DASHBOARD_METADATA_LANGUAGE',
    label: 'Dashboard Title Language',
    description: 'Preferred language code for popular-content titles in the dashboard (e.g. en). A title captured in this language is not overwritten by requests in other languages. Leave blank to always use the most recent request.',
    category: 'Diagnostics',
    type: 'string',
    default: 'en',
  },

  // --- Server (bootstrap, env-only) ---
  {
    key: 'PORT',
    envVar: 'PORT',
    label: 'Server Port',
    description: 'HTTP port the addon listens on',
    category: 'Server',
    type: 'number',
    default: 3232,
    requiresRestart: true,
    envOnly: true,
  },
  {
    key: 'HOST_NAME',
    envVar: 'HOST_NAME',
    label: 'Host Name',
    description: 'Public URL of this addon instance',
    category: 'Server',
    type: 'string',
    default: '',
    requiresRestart: true,
    envOnly: true,
  },
  {
    key: 'DATABASE_URI',
    envVar: 'DATABASE_URI',
    label: 'Database URI',
    description: 'SQLite or PostgreSQL connection string (the writable primary in multi-region deploys)',
    category: 'Server',
    type: 'string',
    default: '',
    sensitive: true,
    requiresRestart: true,
    envOnly: true,
  },
  {
    key: 'DATABASE_READ_URI',
    envVar: 'DATABASE_READ_URI',
    label: 'Database Read Replica URI',
    description: 'Optional PostgreSQL read-replica connection string; reads are served from here, writes still go to DATABASE_URI. Falls back to the primary if unset or unreachable.',
    category: 'Server',
    type: 'string',
    default: '',
    sensitive: true,
    requiresRestart: true,
    envOnly: true,
  },
  {
    key: 'RUN_MIGRATIONS',
    envVar: 'RUN_MIGRATIONS',
    label: 'Run Migrations',
    description: 'Run schema creation (DDL) on startup. Set false on replica-region instances that should not attempt DDL.',
    category: 'Server',
    type: 'boolean',
    default: true,
    requiresRestart: true,
    envOnly: true,
  },
  {
    key: 'REDIS_URL',
    envVar: 'REDIS_URL',
    label: 'Redis URL',
    description: 'Redis connection URL for caching',
    category: 'Server',
    type: 'string',
    default: '',
    sensitive: true,
    requiresRestart: true,
    envOnly: true,
  },
  {
    key: 'ADMIN_KEY',
    envVar: 'ADMIN_KEY',
    label: 'Admin Key',
    description: 'Admin authentication key for the dashboard',
    category: 'Server',
    type: 'string',
    default: '',
    sensitive: true,
    envOnly: true,
  },
  {
    key: 'IMAGE_PROXY_SIGNING_SECRET',
    envVar: 'IMAGE_PROXY_SIGNING_SECRET',
    label: 'Image Proxy Signing Secret',
    description: 'HMAC secret used to sign the /poster, /logo, /background and /landscape proxy URLs. Falls back to ADMIN_KEY; if neither is set, proxy URLs are served unsigned. A purpose-specific key is derived from it, so a signature reveals nothing about the secret itself. Rotating it invalidates every previously signed URL.',
    category: 'Server',
    type: 'string',
    default: '',
    sensitive: true,
    envOnly: true,
  },
  {
    key: 'ADDON_PASSWORD',
    envVar: 'ADDON_PASSWORD',
    label: 'Addon Password',
    description: 'Password required to access the addon configure page',
    category: 'Server',
    type: 'string',
    default: '',
    sensitive: true,
    envOnly: true,
  },

  // --- API Keys ---
  {
    key: 'FANART_API_PROJECT_KEY',
    envVar: 'FANART_API_PROJECT_KEY',
    label: 'Fanart.tv Project Key',
    description: 'Fanart.tv personal/project API key; falls back to the Fanart.tv API key when unset',
    category: 'API Keys',
    type: 'string',
    default: '',
    sensitive: true,
  },

  // --- Cache ---
  {
    key: 'CACHE_CLEANUP_AUTO_ENABLED',
    envVar: 'CACHE_CLEANUP_AUTO_ENABLED',
    label: 'Auto Cache Cleanup',
    description: 'Run the scheduled cache cleanup job automatically',
    category: 'Cache',
    type: 'boolean',
    default: true,
  },
  {
    key: 'CACHE_CLEANUP_QUIET_HOURS_ENABLED',
    envVar: 'CACHE_CLEANUP_QUIET_HOURS_ENABLED',
    label: 'Cleanup Quiet Hours',
    description: 'Pause automatic cache cleanup during quiet hours',
    category: 'Cache',
    type: 'boolean',
    default: false,
    requiresRestart: true,
  },
  {
    key: 'CACHE_CLEANUP_QUIET_HOURS',
    envVar: 'CACHE_CLEANUP_QUIET_HOURS',
    label: 'Cleanup Quiet Hours Range',
    description: 'Time range during which cache cleanup is paused (e.g. 02:00-06:00)',
    category: 'Cache',
    type: 'string',
    default: '02:00-06:00',
    requiresRestart: true,
  },
  {
    key: 'CACHE_RETRY_DELAY',
    envVar: 'CACHE_RETRY_DELAY',
    label: 'Cache Retry Delay (ms)',
    description: 'Milliseconds to wait between cache read/write retries',
    category: 'Cache',
    type: 'number',
    default: 1000,
  },
  {
    key: 'FLIXPATROL_TTL',
    envVar: 'FLIXPATROL_TTL',
    label: 'FlixPatrol TTL (sec)',
    description: 'Override the FlixPatrol catalog cache lifetime in seconds (default refreshes daily)',
    category: 'Cache',
    type: 'number',
    default: '',
  },
  {
    key: 'SIMKL_ACTIVITIES_TTL',
    envVar: 'SIMKL_ACTIVITIES_TTL',
    label: 'Simkl Activities TTL (sec)',
    description: 'Cache lifetime for Simkl activity checks to avoid repeated polling. Also sets how long a newly completed item can still show in catalogs when Hide Simkl Watched is on.',
    category: 'Cache',
    type: 'number',
    default: 21600,
  },
  {
    key: 'TMDB_KEYWORD_EXPORT_TTL',
    envVar: 'TMDB_KEYWORD_EXPORT_TTL',
    label: 'TMDB Keyword Export TTL (sec)',
    description: 'Cache lifetime for the TMDB keyword index export',
    category: 'Cache',
    type: 'number',
    default: 604800,
  },
  {
    key: 'TMDB_NETWORK_EXPORT_TTL',
    envVar: 'TMDB_NETWORK_EXPORT_TTL',
    label: 'TMDB Network Export TTL (sec)',
    description: 'Cache lifetime for the TMDB network index export',
    category: 'Cache',
    type: 'number',
    default: 604800,
  },
  {
    key: 'TMDB_SCRAPED_IMDB_CACHE_MAX',
    envVar: 'TMDB_SCRAPED_IMDB_CACHE_MAX',
    label: 'Scraped IMDb Cache Max',
    description: 'Maximum entries in the scraped TMDB→IMDb in-memory cache',
    category: 'Cache',
    type: 'number',
    default: 10000,
    requiresRestart: true,
  },
  {
    key: 'FANART_CLIENT_CACHE_MAX',
    envVar: 'FANART_CLIENT_CACHE_MAX',
    label: 'Fanart Cache Max',
    description: 'Maximum entries in the in-memory Fanart.tv response cache',
    category: 'Cache',
    type: 'number',
    default: 2000,
    requiresRestart: true,
  },
  {
    key: 'ID_MAPPER_FRANCHISE_MAP_CACHE_MAX_SIZE',
    envVar: 'ID_MAPPER_FRANCHISE_MAP_CACHE_MAX_SIZE',
    label: 'Franchise Map Cache Max',
    description: 'Maximum entries in the franchise map cache',
    category: 'Cache',
    type: 'number',
    default: 20000,
    requiresRestart: true,
  },
  {
    key: 'ID_MAPPER_TMDB_FRANCHISE_INFO_CACHE_MAX_SIZE',
    envVar: 'ID_MAPPER_TMDB_FRANCHISE_INFO_CACHE_MAX_SIZE',
    label: 'TMDB Franchise Info Cache Max',
    description: 'Maximum entries in the TMDB franchise info cache',
    category: 'Cache',
    type: 'number',
    default: 3000,
    requiresRestart: true,
  },
  {
    key: 'ID_MAPPER_TMDB_SEASON_CACHE_MAX_SIZE',
    envVar: 'ID_MAPPER_TMDB_SEASON_CACHE_MAX_SIZE',
    label: 'TMDB Season Cache Max',
    description: 'Maximum entries in the TMDB season mapping cache',
    category: 'Cache',
    type: 'number',
    default: 15000,
    requiresRestart: true,
  },
  {
    key: 'ID_MAPPER_KITSU_TO_IMDB_CACHE_MAX_SIZE',
    envVar: 'ID_MAPPER_KITSU_TO_IMDB_CACHE_MAX_SIZE',
    label: 'Kitsu→IMDb Cache Max',
    description: 'Maximum entries in the Kitsu→IMDb mapping cache',
    category: 'Cache',
    type: 'number',
    default: 20000,
    requiresRestart: true,
  },

  // --- Features ---
  {
    key: 'FLIXPATROL_CATALOG_URL',
    envVar: 'FLIXPATROL_CATALOG_URL',
    label: 'FlixPatrol Catalog URL',
    description: 'Base URL for FlixPatrol crawler catalog data',
    category: 'Features',
    type: 'string',
    default: '',
  },
  {
    key: 'ENABLE_BUILTIN_POSTER_CACHE',
    envVar: 'ENABLE_BUILTIN_POSTER_CACHE',
    label: 'Built-in Image Cache',
    description: 'Cache images on disk and serve them from /poster-cache. Caches posters by default; enable the options below to cache more artwork.',
    category: 'Features',
    type: 'boolean',
    default: false,
    requiresRestart: true,
  },
  {
    key: 'POSTER_CACHE_BACKGROUNDS',
    envVar: 'POSTER_CACHE_BACKGROUNDS',
    label: 'Cache Backgrounds',
    description: 'Also cache background artwork. These are the largest images the addon serves, so this is the biggest bandwidth saving. Covers custom-art backgrounds too.',
    category: 'Features',
    type: 'boolean',
    default: false,
  },
  {
    key: 'POSTER_CACHE_LANDSCAPE_POSTERS',
    envVar: 'POSTER_CACHE_LANDSCAPE_POSTERS',
    label: 'Cache Landscape Posters',
    description: 'Also cache landscape poster artwork.',
    category: 'Features',
    type: 'boolean',
    default: false,
  },
  {
    key: 'POSTER_CACHE_LOGOS',
    envVar: 'POSTER_CACHE_LOGOS',
    label: 'Cache Logos',
    description: 'Also cache logo artwork. Many small files. Covers custom-art logos too.',
    category: 'Features',
    type: 'boolean',
    default: false,
  },
  {
    key: 'POSTER_CACHE_THUMBNAILS',
    envVar: 'POSTER_CACHE_THUMBNAILS',
    label: 'Cache Episode Thumbnails',
    description: 'Also cache episode thumbnails. By far the most numerous class — a single long-running series can add hundreds of images — so expect disk usage to grow quickly.',
    category: 'Features',
    type: 'boolean',
    default: false,
  },
  {
    key: 'POSTER_CACHE_PROCESSED_IMAGES',
    envVar: 'POSTER_CACHE_PROCESSED_IMAGES',
    label: 'Cache Processed Images',
    description: 'Cache the images the addon renders itself — rating-overlaid posters and the blur, resize and banner-to-background transforms. Without it they re-render on every view.',
    category: 'Features',
    type: 'boolean',
    default: true,
  },
  {
    key: 'PREFER_SMALLER_POSTERS_TMDB',
    envVar: 'PREFER_SMALLER_POSTERS_TMDB',
    label: 'Prefer Smaller TMDB Posters',
    description: 'Request TMDB posters at w600_and_h900_bestv2 instead of the uploader\'s original file. ON by default and recommended. Posters are usually rendered in small cards and the resolution should already be sufficient, expect exponentially more disk usage/bandwidth if disabled.',
    category: 'Features',
    type: 'boolean',
    default: true,
  },
  {
    key: 'PREFER_SMALLER_LOGOS_TMDB',
    envVar: 'PREFER_SMALLER_LOGOS_TMDB',
    label: 'Prefer Smaller TMDB Logos',
    description: 'Request TMDB logos at w500 instead of the uploader\'s original file. Off by default. Originals are lossless PNGs with a median width of 1683px, for artwork rendered far smaller, so this is around 12x less data. Changing this does not affect meta already in the cache until META_TTL expires; the superseded images stay on disk unreferenced and are reclaimed automatically as they age out.',
    category: 'Features',
    type: 'boolean',
    default: false,
  },
  {
    key: 'PREFER_SMALLER_BACKDROPS_TMDB',
    envVar: 'PREFER_SMALLER_BACKDROPS_TMDB',
    label: 'Prefer Smaller TMDB Backdrops',
    description: 'Request TMDB backgrounds and landscape posters at w1280 instead of the original. Off by default, not recommended for high resolution displays.',
    category: 'Features',
    type: 'boolean',
    default: false,
  },
  {
    key: 'PREFER_SMALLER_LANDSCAPE_TMDB',
    envVar: 'PREFER_SMALLER_LANDSCAPE_TMDB',
    label: 'Prefer Smaller TMDB Landscape Posters',
    description: 'Request TMDB landscape posters at w780 instead of the original. Off by default. Independent of Prefer Smaller TMDB Backdrops: clients render a landscape poster as a catalog tile a few hundred px wide rather than full-screen, so it tolerates a smaller rendition than a background does.',
    category: 'Features',
    type: 'boolean',
    default: false,
  },
  {
    key: 'POSTER_PROXY_ALLOW_PRIVATE',
    envVar: 'POSTER_PROXY_ALLOW_PRIVATE',
    label: 'Allow Private Art Hosts',
    description: 'Let a signed art URL reach a private/LAN address, so a self-hosted art provider needs no allowlist entry. Turn it OFF on a public instance: art patterns are user-supplied, so any user could point one inside your network.',
    category: 'Features',
    type: 'boolean',
    default: true,
  },
  {
    key: 'POSTER_CACHE_ALLOWED_HOSTS',
    envVar: 'POSTER_CACHE_ALLOWED_HOSTS',
    label: 'Image Cache Allowed Private Hosts',
    description: 'Comma-separated hosts the cache may fetch from even when they resolve to a private/LAN address, such as a self-hosted art provider. Everything else stays blocked.',
    category: 'Features',
    type: 'string',
    default: '',
  },
  {
    key: 'POSTER_CACHE_MAX_SIZE',
    envVar: 'POSTER_CACHE_MAX_SIZE',
    label: 'Image Cache Max Size',
    description: 'Disk budget for the image cache (e.g. 10g, 512m). Least-recently-used images are evicted once exceeded.',
    category: 'Features',
    type: 'string',
    default: '10g',
    validate: (v: string) => /^\s*\d+(\.\d+)?\s*(b|k|kb|m|mb|g|gb|t|tb)?\s*$/i.test(v),
  },
  {
    key: 'POSTER_CACHE_MEMORY_SIZE',
    envVar: 'POSTER_CACHE_MEMORY_SIZE',
    label: 'Image Cache Memory Size',
    description: 'RAM held for the hottest images, on top of the disk cache (e.g. 128m). Serving from memory skips both the disk read and its per-request allocation. Set to 0 to use disk only.',
    category: 'Features',
    type: 'string',
    default: '128m',
    validate: (v: string) => /^\s*\d+(\.\d+)?\s*(b|k|kb|m|mb|g|gb)?\s*$/i.test(v),
  },
  {
    key: 'POSTER_CACHE_TTL_DAYS',
    envVar: 'POSTER_CACHE_TTL_DAYS',
    label: 'Image Cache Validity (Days)',
    description: 'How long a cached image stays fresh, where a provider has no rule or built-in policy of its own. Fractional values are allowed (0.5 = 12 hours); 0 never expires.',
    category: 'Features',
    type: 'number',
    default: 30,
    min: 0,
  },
  {
    key: 'POSTER_CACHE_INFER_TTL',
    envVar: 'POSTER_CACHE_INFER_TTL',
    label: 'Follow Each Source\'s Own Validity',
    description: 'Derives an image\'s validity from the headers its source sent, rather than the flat value above. Only applies where a provider has no rule and no built-in policy.',
    category: 'Features',
    type: 'boolean',
    default: false,
  },
  {
    key: 'POSTER_CACHE_PROVIDER_PRESETS',
    envVar: 'POSTER_CACHE_PROVIDER_PRESETS',
    label: 'Use Built-In Provider Policies',
    description: 'Each known provider ships with a validity measured from what it actually sends, so rating posters stay current with nothing configured. Applies to stored images and to the Cache-Control the art proxy sends on passed-through art. A rule below always wins.',
    category: 'Features',
    type: 'boolean',
    default: true,
  },
  {
    key: 'POSTER_CACHE_PROVIDER_POLICIES',
    envVar: 'POSTER_CACHE_PROVIDER_POLICIES',
    label: 'Per-Provider Cache Policies',
    description: 'Per-provider overrides as a JSON list — e.g. [{"domain":"btttr.cc","policy":"custom","ttl":"6h"}]. Policies: "default", "infer", "custom" with a "ttl", or "bypass". Governs how long an image is stored and, on art the proxy passes through without storing, the Cache-Control it is served with. Easier to edit under Advanced… on the Image Cache card.',
    category: 'Features',
    type: 'string',
    default: '',
    validate: (v: string) => parseProviderPolicies(v) !== null,
  },
  {
    key: 'POSTER_PROXY_MAX_AGE_DAYS',
    envVar: 'POSTER_PROXY_MAX_AGE_DAYS',
    label: 'Art Proxy Client Cache (Days)',
    description: 'How long players and browsers may keep an image from the art proxy routes. Short by default because such art is often addressed by title, so the bytes can change while the URL does not. A per-provider rule overrides it outright. Fractional values are allowed; 0 means a year.',
    category: 'Features',
    type: 'number',
    default: 1,
    min: 0,
  },
  {
    key: 'POSTER_PROXY_FOLLOW_UPSTREAM',
    envVar: 'POSTER_PROXY_FOLLOW_UPSTREAM',
    label: 'Art Proxy Follows the Source\'s Cache-Control',
    description: 'Forwards the provider\'s Cache-Control and CDN-Cache-Control verbatim on passed-through images, removing the ceiling above and the built-in provider policies with it. A rule you set yourself still wins. Rarely needed — a provider sending a year-long max-age would then pin its art in your CDN for that long.',
    category: 'Features',
    type: 'boolean',
    default: false,
  },
  {
    key: 'POSTER_CACHE_INACTIVE_DAYS',
    envVar: 'POSTER_CACHE_INACTIVE_DAYS',
    label: 'Image Cache Inactive Days',
    description: 'Drop cached images that have not been requested for this many days',
    category: 'Features',
    type: 'number',
    default: 30,
    min: 1,
  },
  {
    key: 'POSTER_CACHE_MAX_OBJECT_BYTES',
    envVar: 'POSTER_CACHE_MAX_OBJECT_BYTES',
    label: 'Image Cache Max Object Size',
    description: 'Images larger than this stream through without being cached (e.g. 20m)',
    category: 'Features',
    type: 'string',
    default: '20m',
    validate: (v: string) => /^\s*\d+(\.\d+)?\s*(b|k|kb|m|mb|g|gb)?\s*$/i.test(v),
  },
  {
    key: 'POSTER_CACHE_FETCH_CONCURRENCY',
    envVar: 'POSTER_CACHE_FETCH_CONCURRENCY',
    label: 'Image Fetch Concurrency',
    description: 'Maximum simultaneous downloads of uncached images. Each briefly holds an image in memory, so this caps peak memory during a burst of misses.',
    category: 'Features',
    type: 'number',
    default: 128,
    min: 1,
  },
  {
    key: 'POSTER_CACHE_TLS_SESSIONS',
    envVar: 'POSTER_CACHE_TLS_SESSIONS',
    label: 'Image Provider TLS Session Cache',
    description: 'Resumable TLS sessions kept per image provider. Each one holds a 64 KiB buffer, so raising it trades memory for fewer full handshakes. 0 disables resumption.',
    category: 'Features',
    type: 'number',
    default: 10,
    min: 0,
  },
  {
    key: 'POSTER_CACHE_STREAM_THRESHOLD',
    envVar: 'POSTER_CACHE_STREAM_THRESHOLD',
    label: 'Image Stream Threshold',
    description: 'Cached images larger than this are streamed from disk instead of read into memory, so bursts of large artwork cannot pile up on the heap (e.g. 256k).',
    category: 'Features',
    type: 'string',
    default: '256k',
    validate: (v: string) => /^\s*\d+(\.\d+)?\s*(b|k|kb|m|mb|g|gb)?\s*$/i.test(v),
  },
  {
    key: 'POSTER_CACHE_AGENT_TTL_MS',
    envVar: 'POSTER_CACHE_AGENT_TTL_MS',
    label: 'Image Upstream Connection TTL (ms)',
    description: 'How long a validated host\'s addresses and pooled connections are reused before it is re-resolved. Pooling avoids a TLS handshake per image. Advanced tuning.',
    category: 'Features',
    type: 'number',
    default: 60000,
    min: 1,
  },
  {
    key: 'POSTER_CACHE_AGENT_MAX',
    envVar: 'POSTER_CACHE_AGENT_MAX',
    label: 'Image Upstream Connection Pool Size',
    description: 'Maximum distinct upstream hosts kept in the connection pool, bounding memory and open sockets. The least recently added are evicted. Advanced tuning.',
    category: 'Features',
    type: 'number',
    default: 512,
    min: 1,
  },
  {
    key: 'POSTER_CACHE_LOG_REQUESTS',
    envVar: 'POSTER_CACHE_LOG_REQUESTS',
    label: 'Log Every Image Request',
    description: 'Debugging aid. Off by default because at a few thousand images a second it fills the log buffer and pushes out everything else. A one-line summary is logged each minute regardless.',
    category: 'Features',
    type: 'boolean',
    default: false,
  },
  {
    key: 'POSTER_CACHE_DIR',
    envVar: 'POSTER_CACHE_DIR',
    label: 'Image Cache Directory',
    description: 'Where cached images are stored. Defaults to addon/data/poster-cache, inside the existing data volume.',
    category: 'Features',
    type: 'string',
    default: '',
    requiresRestart: true,
  },
  {
    key: 'POSTER_CACHE_IMPORT_NGINX_DIR',
    envVar: 'POSTER_CACHE_IMPORT_NGINX_DIR',
    label: 'Import nginx Poster Cache',
    description: 'Usually leave empty: a cache from the old bundled nginx proxy is detected and imported automatically on first start. Set "off" to skip it.',
    category: 'Features',
    type: 'string',
    default: '',
    requiresRestart: true,
  },
  {
    key: 'ENABLE_UI_RESTART',
    envVar: 'ENABLE_UI_RESTART',
    label: 'Enable Dashboard Restart',
    description: 'Allow restarting the addon from the dashboard (needs a process manager that auto-restarts on exit)',
    category: 'Features',
    type: 'boolean',
    default: false,
  },
  {
    key: 'MAL_PAGE_SIZE',
    envVar: 'MAL_PAGE_SIZE',
    label: 'MAL Page Size',
    description: 'Number of items per MyAnimeList catalog page',
    category: 'Features',
    type: 'number',
    default: 25,
  },

  // --- MAL Warming ---
  {
    key: 'MAL_WARMUP_PRIORITY',
    envVar: 'MAL_WARMUP_PRIORITY',
    label: 'MAL Warm Priority Genres',
    description: 'Warm priority genre pages during MAL warming',
    category: 'MAL Warming',
    type: 'boolean',
    default: true,
  },
  {
    key: 'MAL_WARMUP_SCHEDULE',
    envVar: 'MAL_WARMUP_SCHEDULE',
    label: 'MAL Warm Schedule',
    description: 'Warm the seasonal/schedule catalogs during MAL warming',
    category: 'MAL Warming',
    type: 'boolean',
    default: true,
  },
  {
    key: 'MAL_WARMUP_SFW',
    envVar: 'MAL_WARMUP_SFW',
    label: 'MAL Warm SFW Only',
    description: 'Restrict MAL warming to safe-for-work entries',
    category: 'MAL Warming',
    type: 'boolean',
    default: true,
  },

  // --- Rate Limiting ---
  {
    key: 'API_KEY_TEST_TIMEOUT_MS',
    envVar: 'API_KEY_TEST_TIMEOUT_MS',
    label: 'API Key Test Timeout (ms)',
    description: 'Timeout for validating user-supplied API keys',
    category: 'Rate Limiting',
    type: 'number',
    default: 8000,
  },
  {
    key: 'META_CONCURRENCY',
    envVar: 'META_CONCURRENCY',
    label: 'Meta Concurrency',
    description: 'Max concurrent metadata enrichment requests (0 = library default)',
    category: 'Rate Limiting',
    type: 'number',
    default: 0,
    requiresRestart: true,
  },
  {
    key: 'TRAKT_CONCURRENCY',
    envVar: 'TRAKT_CONCURRENCY',
    label: 'Trakt Concurrency',
    description: 'Max parallel Trakt requests (10-15 recommended for self-hosters)',
    category: 'Rate Limiting',
    type: 'number',
    default: 15,
    requiresRestart: true,
  },
  {
    key: 'TRAKT_MIN_TIME',
    envVar: 'TRAKT_MIN_TIME',
    label: 'Trakt Min Interval (ms)',
    description: 'Minimum milliseconds between Trakt requests',
    category: 'Rate Limiting',
    type: 'number',
    default: 50,
    requiresRestart: true,
  },
  {
    key: 'TRAKT_GET_WINDOW_LIMIT',
    envVar: 'TRAKT_GET_WINDOW_LIMIT',
    label: 'Trakt GET Window Limit',
    description: 'Max Trakt GET requests allowed per rate-limit window',
    category: 'Rate Limiting',
    type: 'number',
    default: '',
    requiresRestart: true,
  },
  {
    key: 'TRAKT_GET_WINDOW_MS',
    envVar: 'TRAKT_GET_WINDOW_MS',
    label: 'Trakt GET Window (ms)',
    description: 'Length of the Trakt GET rate-limit window in milliseconds',
    category: 'Rate Limiting',
    type: 'number',
    default: '',
    requiresRestart: true,
  },
  {
    key: 'TRAKT_AUTHED_API_WRITE_INTERVAL_MS',
    envVar: 'TRAKT_AUTHED_API_WRITE_INTERVAL_MS',
    label: 'Trakt Write Interval (ms)',
    description: 'Minimum interval between authenticated Trakt write requests',
    category: 'Rate Limiting',
    type: 'number',
    default: 1000,
    requiresRestart: true,
  },
  {
    key: 'TRAKT_RATE_LIMIT_BUFFER_MS',
    envVar: 'TRAKT_RATE_LIMIT_BUFFER_MS',
    label: 'Trakt Rate Limit Buffer (ms)',
    description: 'Safety buffer added when honoring Trakt rate-limit headers',
    category: 'Rate Limiting',
    type: 'number',
    default: 1000,
    requiresRestart: true,
  },
  {
    key: 'TRAKT_RATE_LIMIT_SAFETY_RATIO',
    envVar: 'TRAKT_RATE_LIMIT_SAFETY_RATIO',
    label: 'Trakt Rate Limit Safety Ratio',
    description: 'Fraction of the Trakt rate limit to use (0-1)',
    category: 'Rate Limiting',
    type: 'number',
    default: 0.85,
    requiresRestart: true,
  },
  {
    key: 'TRAKT_OAUTH_STATE_TTL_MS',
    envVar: 'TRAKT_OAUTH_STATE_TTL_MS',
    label: 'Trakt OAuth State TTL (ms)',
    description: 'Lifetime of the Trakt OAuth state token during login',
    category: 'Rate Limiting',
    type: 'number',
    default: 600000,
    requiresRestart: true,
  },
  {
    key: 'TEST_API_KEY_MAX_LENGTH',
    envVar: 'TEST_API_KEY_MAX_LENGTH',
    label: 'API Key Test Max Length',
    description: 'Maximum accepted length when validating a user-supplied API key',
    category: 'Rate Limiting',
    type: 'number',
    default: 128,
  },

  // --- Data Updates ---
  {
    key: 'ANIME_LIST_XML_UPDATE_INTERVAL_HOURS',
    envVar: 'ANIME_LIST_XML_UPDATE_INTERVAL_HOURS',
    label: 'Anime List XML Update (hrs)',
    description: 'Hours between anime-list XML mapping refreshes',
    category: 'Data Updates',
    type: 'number',
    default: 24,
    requiresRestart: true,
  },
  {
    key: 'LOCAL_ANIME_SEARCH_UPDATE_INTERVAL_HOURS',
    envVar: 'LOCAL_ANIME_SEARCH_UPDATE_INTERVAL_HOURS',
    label: 'Local Anime Search Update (hrs)',
    description: 'Hours between refreshes of the local anime title index',
    category: 'Data Updates',
    type: 'number',
    default: 24,
    requiresRestart: true,
  },
  {
    key: 'LOCAL_ANIME_SEARCH_URL',
    envVar: 'LOCAL_ANIME_SEARCH_URL',
    label: 'Local Anime Search Index URL',
    description: 'Override the remote anime-index.json source used to refresh the local title index',
    category: 'Data Updates',
    type: 'string',
    default: 'https://cdn.jsdelivr.net/gh/subhajeetch-fl/anime-mapper@main/data/anime-index.json',
    requiresRestart: true,
  },
  {
    key: 'LOCAL_ANIME_SEARCH_KITSU_FALLBACK',
    envVar: 'LOCAL_ANIME_SEARCH_KITSU_FALLBACK',
    label: 'Local Anime Search Kitsu Fallback',
    description: 'Use Kitsu text search only when the local anime index returns zero results or cannot load',
    category: 'Data Updates',
    type: 'boolean',
    default: true,
  },
  {
    key: 'TMDB_KEYWORD_EXPORT_LOOKBACK_DAYS',
    envVar: 'TMDB_KEYWORD_EXPORT_LOOKBACK_DAYS',
    label: 'TMDB Keyword Lookback (days)',
    description: 'How many days back to pull the TMDB keyword export',
    category: 'Data Updates',
    type: 'number',
    default: 7,
  },
  {
    key: 'TMDB_NETWORK_EXPORT_LOOKBACK_DAYS',
    envVar: 'TMDB_NETWORK_EXPORT_LOOKBACK_DAYS',
    label: 'TMDB Network Lookback (days)',
    description: 'How many days back to pull the TMDB network export',
    category: 'Data Updates',
    type: 'number',
    default: 7,
  },

  // --- Proxy ---
  {
    key: 'GEMINI_HTTPS_PROXY',
    envVar: 'GEMINI_HTTPS_PROXY',
    label: 'Gemini HTTPS Proxy',
    description: 'HTTPS proxy URL for Google Gemini requests',
    category: 'Proxy',
    type: 'string',
    default: '',
  },
  {
    key: 'GEMINI_HTTP_PROXY',
    envVar: 'GEMINI_HTTP_PROXY',
    label: 'Gemini HTTP Proxy',
    description: 'HTTP proxy URL for Google Gemini requests',
    category: 'Proxy',
    type: 'string',
    default: '',
  },
  {
    key: 'OPENROUTER_HTTPS_PROXY',
    envVar: 'OPENROUTER_HTTPS_PROXY',
    label: 'OpenRouter HTTPS Proxy',
    description: 'HTTPS proxy URL for OpenRouter requests',
    category: 'Proxy',
    type: 'string',
    default: '',
  },
  {
    key: 'OPENROUTER_HTTP_PROXY',
    envVar: 'OPENROUTER_HTTP_PROXY',
    label: 'OpenRouter HTTP Proxy',
    description: 'HTTP proxy URL for OpenRouter requests',
    category: 'Proxy',
    type: 'string',
    default: '',
  },
  {
    key: 'SIMKL_SEARCH_RESULT_LIMIT',
    envVar: 'SIMKL_SEARCH_RESULT_LIMIT',
    label: 'Simkl Search Result Limit',
    description: 'How many Simkl search results to hydrate into full results. Each one costs a TMDB lookup, so raising this makes searches slower.',
    category: 'Features',
    type: 'number',
    default: 20,
    min: 1,
    max: 50,
  },
  {
    key: 'SIMKL_ANIME_SEARCH_RESULT_LIMIT',
    envVar: 'SIMKL_ANIME_SEARCH_RESULT_LIMIT',
    label: 'Simkl Anime Search Result Limit',
    description: 'How many Simkl anime search results to hydrate into full results. Ids are mapped in memory and metas are fetched in one batch, so this costs less than the movie and series limit.',
    category: 'Features',
    type: 'number',
    default: 20,
    min: 1,
    max: 50,
  },
  {
    key: 'IMDB_SUGGESTION_TIMEOUT_MS',
    envVar: 'IMDB_SUGGESTION_TIMEOUT_MS',
    label: 'IMDb Suggestion Timeout',
    description: 'How long to wait for IMDb\'s suggestion endpoint before giving up on a search, in milliseconds.',
    category: 'Features',
    type: 'number',
    default: 5000,
    min: 500,
  },
  {
    key: 'IMDB_SUGGESTION_TTL_SECONDS',
    envVar: 'IMDB_SUGGESTION_TTL_SECONDS',
    label: 'IMDb Suggestion Cache TTL',
    description: 'How long a query\'s IMDb suggestion results are cached, in seconds. The list is global, so the cache is shared by every user.',
    category: 'Cache',
    type: 'number',
    default: 86400,
    min: 0,
  },
  {
    key: 'IMDB_SUGGESTION_RESULT_LIMIT',
    envVar: 'IMDB_SUGGESTION_RESULT_LIMIT',
    label: 'IMDb Suggestion Result Limit',
    description: 'How many IMDb suggestions to hydrate into full results. Each one costs a TMDB lookup, so raising this makes searches slower.',
    category: 'Features',
    type: 'number',
    default: 12,
    min: 1,
    max: 50,
  },
  {
    key: 'MDBLIST_SOCKS_PROXY_URL',
    envVar: 'MDBLIST_SOCKS_PROXY_URL',
    label: 'MDBList SOCKS Proxy',
    description: 'SOCKS proxy URL specifically for MDBList requests',
    category: 'Proxy',
    type: 'string',
    default: '',
    requiresRestart: true,
  },
  {
    key: 'TRAKT_PROXY_URL',
    envVar: 'TRAKT_PROXY_URL',
    label: 'Trakt Proxy URL',
    description: 'Proxy URL specifically for Trakt requests',
    category: 'Proxy',
    type: 'string',
    default: '',
    requiresRestart: true,
  },

  // --- Diagnostics ---
  {
    key: 'HEAP_DIAGNOSTICS_DIR',
    envVar: 'HEAP_DIAGNOSTICS_DIR',
    label: 'Heap Diagnostics Dir',
    description: 'Directory for heap snapshot/diagnostics output (defaults to addon/data/diagnostics)',
    category: 'Diagnostics',
    type: 'string',
    default: '',
    requiresRestart: true,
  },
  {
    key: 'HEAP_LOG_INTERVAL_MIN',
    envVar: 'HEAP_LOG_INTERVAL_MIN',
    label: 'Heap Log Interval (min)',
    description: 'Minutes between heap usage log samples (0 = disabled)',
    category: 'Diagnostics',
    type: 'number',
    default: 0,
    requiresRestart: true,
  },
  {
    key: 'KEYS_TO_KEEP_AFTER_PRUNE',
    envVar: 'KEYS_TO_KEEP_AFTER_PRUNE',
    label: 'Keys To Keep After Prune',
    description: 'Number of tracked cache keys retained when pruning analytics',
    category: 'Diagnostics',
    type: 'number',
    default: 6000,
  },
  {
    key: 'LOG_BUFFER_MAX_ENTRIES',
    envVar: 'LOG_BUFFER_MAX_ENTRIES',
    label: 'Log Buffer Max Entries',
    description: 'Maximum log entries kept in memory (supersedes Log Buffer Size)',
    category: 'Diagnostics',
    type: 'number',
    default: 100000,
    requiresRestart: true,
  },
  {
    key: 'LOG_BUFFER_MAX_BYTES',
    envVar: 'LOG_BUFFER_MAX_BYTES',
    label: 'Log Buffer Max Bytes',
    description: 'Maximum bytes of log data kept in memory',
    category: 'Diagnostics',
    type: 'number',
    default: 67108864,
    requiresRestart: true,
  },

  // --- Server (bootstrap, env-only) ---
  {
    key: 'REDIS_READY_TIMEOUT_MS',
    envVar: 'REDIS_READY_TIMEOUT_MS',
    label: 'Redis Ready Timeout (ms)',
    description: 'Milliseconds to wait for Redis to become ready at startup',
    category: 'Server',
    type: 'number',
    default: 15000,
    requiresRestart: true,
    envOnly: true,
  },

  // --- MovieLens ---
  {
    key: 'MOVIELENS_CRED_KEY',
    envVar: 'MOVIELENS_CRED_KEY',
    label: 'MovieLens Credential Key',
    description: 'AES key encrypting stored MovieLens passwords. Required for the integration. Rotating it orphans all stored credentials.',
    category: 'MovieLens',
    type: 'string',
    default: '',
    sensitive: true,
    envOnly: true,
  },
  {
    key: 'ENABLE_MOVIELENS_SYNC',
    envVar: 'ENABLE_MOVIELENS_SYNC',
    label: 'Enable MovieLens Re-sync',
    description: 'Enable the scheduled background job that re-syncs ratings into connected MovieLens accounts',
    category: 'MovieLens',
    type: 'boolean',
    default: true,
    requiresRestart: true,
  },
  {
    key: 'MOVIELENS_SYNC_INTERVAL_HOURS',
    envVar: 'MOVIELENS_SYNC_INTERVAL_HOURS',
    label: 'MovieLens Re-sync Interval (hours)',
    description: 'How often the scheduled job re-syncs ratings into MovieLens',
    category: 'MovieLens',
    type: 'number',
    default: 24,
    requiresRestart: true,
    min: 1,
  },
  {
    key: 'MOVIELENS_MANUAL_SYNC_COOLDOWN_SECONDS',
    envVar: 'MOVIELENS_MANUAL_SYNC_COOLDOWN_SECONDS',
    label: 'MovieLens Manual Sync Cooldown (seconds)',
    description: 'Minimum time between user-triggered "Import ratings" runs',
    category: 'MovieLens',
    type: 'number',
    default: 21600,
  },
  {
    key: 'MOVIELENS_API_BASE',
    envVar: 'MOVIELENS_API_BASE',
    label: 'MovieLens API Base URL',
    description: 'Base URL for the MovieLens API',
    category: 'MovieLens',
    type: 'string',
    default: 'https://movielens.org/api',
  },
  {
    key: 'MOVIELENS_REQUEST_TIMEOUT_MS',
    envVar: 'MOVIELENS_REQUEST_TIMEOUT_MS',
    label: 'MovieLens Request Timeout (ms)',
    description: 'Timeout for requests to the MovieLens API',
    category: 'MovieLens',
    type: 'number',
    default: 25000,
  },
  {
    key: 'MOVIELENS_USER_AGENT',
    envVar: 'MOVIELENS_USER_AGENT',
    label: 'MovieLens User-Agent',
    description: 'User-Agent header sent to MovieLens',
    category: 'MovieLens',
    type: 'string',
    default: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36',
  },
  {
    key: 'MOVIELENS_LOGIN_REFERER',
    envVar: 'MOVIELENS_LOGIN_REFERER',
    label: 'MovieLens Login Referer',
    description: 'Referer header used for the MovieLens login request',
    category: 'MovieLens',
    type: 'string',
    default: 'https://movielens.org/login',
  },
  {
    key: 'MOVIELENS_IMPORT_REFERER',
    envVar: 'MOVIELENS_IMPORT_REFERER',
    label: 'MovieLens Import Referer',
    description: 'Referer header used for the MovieLens CSV import request',
    category: 'MovieLens',
    type: 'string',
    default: 'https://movielens.org/profile/settings/import-export',
  },
  {
    key: 'MOVIELENS_CATALOG_TTL_SECONDS',
    envVar: 'MOVIELENS_CATALOG_TTL_SECONDS',
    label: 'MovieLens Catalog TTL',
    description: 'Time-to-live for MovieLens catalog cache entries in seconds',
    category: 'Cache',
    type: 'number',
    default: 3600,
  },
  {
    key: 'MOVIELENS_USERMETA_TTL_SECONDS',
    envVar: 'MOVIELENS_USERMETA_TTL_SECONDS',
    legacyEnvVar: 'MOVIELENS_GROUPTAGS_TTL_SECONDS',
    label: 'MovieLens User Metadata TTL',
    description: 'Time-to-live in seconds for cached MovieLens account metadata (recommendation engine and taste tags)',
    category: 'Cache',
    type: 'number',
    default: 43200,
  },
  {
    key: 'MOVIELENS_LIST_MAX_PAGES',
    envVar: 'MOVIELENS_LIST_MAX_PAGES',
    label: 'MovieLens List Max Pages',
    description: 'Safety cap on pages fetched when paginating a MovieLens list',
    category: 'MovieLens',
    type: 'number',
    default: 50,
  },
  {
    key: 'MDBLIST_RATINGS_PAGE_SIZE',
    envVar: 'MDBLIST_RATINGS_PAGE_SIZE',
    label: 'MDBList Ratings Page Size',
    description: 'Page size when importing personal ratings from MDBList',
    category: 'MovieLens',
    type: 'number',
    default: 1000,
  },
  {
    key: 'MDBLIST_RATINGS_MAX_PAGES',
    envVar: 'MDBLIST_RATINGS_MAX_PAGES',
    label: 'MDBList Ratings Max Pages',
    description: 'Safety cap on pages fetched when importing MDBList ratings',
    category: 'MovieLens',
    type: 'number',
    default: 100,
  },
  {
    key: 'METAHUB_IMAGE_EXISTS_TTL_SECONDS',
    envVar: 'METAHUB_IMAGE_EXISTS_TTL_SECONDS',
    label: 'Metahub Image-Exists TTL',
    description: 'Time-to-live for cached metahub logo/image existence checks in seconds',
    category: 'Cache',
    type: 'number',
    default: 86400,
  },
  {
    key: 'METAHUB_IMAGE_ERROR_TTL_SECONDS',
    envVar: 'METAHUB_IMAGE_ERROR_TTL_SECONDS',
    label: 'Metahub Image-Exists Error TTL',
    description: 'How long an unreachable metahub check is remembered. Kept short so a brief outage suppresses logos for minutes rather than the full day the confirmed-result TTL would apply.',
    category: 'Cache',
    type: 'number',
    default: 300,
    min: 1,
  },
  {
    key: 'METAHUB_IMAGE_HEAD_TIMEOUT_MS',
    envVar: 'METAHUB_IMAGE_HEAD_TIMEOUT_MS',
    label: 'Metahub Image-Exists Timeout (ms)',
    description: 'Timeout for the metahub image existence HEAD request',
    category: 'Cache',
    type: 'number',
    default: 4000,
  },
  {
    key: 'CACHE_EPOCH',
    envVar: 'CACHE_EPOCH',
    label: 'Cache Epoch',
    description: 'Overrides the compiled-in cache epoch. Caches are keyed by this number rather than by the addon version, so upgrades no longer discard good data. Raise it to force a full rebuild of derived caches without waiting for a release; anything stored under a lower epoch is dropped on restart.',
    category: 'Cache',
    type: 'number',
    default: DEFAULT_CACHE_EPOCH,
    min: 1,
    requiresRestart: true,
  },

  // --- Meta Cold Store (disk L2 for stable metadata) ---
  {
    key: 'META_COLD_STORE_ENABLED',
    envVar: 'META_COLD_STORE_ENABLED',
    label: 'Meta Cold Store',
    description: 'Persist stable metadata (old films, ended series) in an on-disk SQLite tier to reduce upstream API calls',
    category: 'Cache',
    type: 'boolean',
    default: false,
    requiresRestart: true,
  },
  {
    key: 'META_COLD_STORE_PATH',
    envVar: 'META_COLD_STORE_PATH',
    label: 'Cold Store Path',
    description: 'File path for the dedicated meta cold-store SQLite database',
    category: 'Cache',
    type: 'string',
    default: '',
    requiresRestart: true,
  },
  {
    key: 'META_COLD_STORE_MAX_BYTES',
    envVar: 'META_COLD_STORE_MAX_BYTES',
    label: 'Cold Store Max Size',
    description: 'Disk budget before LRU eviction (e.g. 2gb)',
    category: 'Cache',
    type: 'string',
    default: '2gb',
    validate: (v: string) => /^\s*\d+(\.\d+)?\s*(b|k|kb|m|mb|g|gb|t|tb)?\s*$/i.test(v),
  },
  {
    key: 'META_COLD_STORE_COMPRESSION',
    envVar: 'META_COLD_STORE_COMPRESSION',
    label: 'Cold Store Compression',
    description: 'lz4-compress cold-store payloads above the compression threshold. Roughly halves disk usage (the saving is concentrated in the large cast and links components). Safe to change at any time — existing entries stay readable.',
    category: 'Cache',
    type: 'boolean',
    default: true,
  },
  {
    key: 'COLD_TTL_FROZEN',
    envVar: 'COLD_TTL_FROZEN',
    label: 'Cold TTL (frozen tier)',
    description: 'Disk TTL for very old/frozen entries (e.g. 180d)',
    category: 'Cache',
    type: 'string',
    default: '180d',
    validate: (v: string) => /^\s*\d+(\.\d+)?\s*(s|sec|m|min|h|hr|d|w|y)?\s*$/i.test(v),
  },
  {
    key: 'COLD_TTL_STABLE',
    envVar: 'COLD_TTL_STABLE',
    label: 'Cold TTL (stable tier)',
    description: 'Disk TTL for recently-finished stable entries (e.g. 60d)',
    category: 'Cache',
    type: 'string',
    default: '60d',
    validate: (v: string) => /^\s*\d+(\.\d+)?\s*(s|sec|m|min|h|hr|d|w|y)?\s*$/i.test(v),
  },
  {
    key: 'SETTLE_MOVIE',
    envVar: 'SETTLE_MOVIE',
    label: 'Movie Settle Window',
    description: 'Minimum age since release before a movie is disk-eligible (e.g. 180d)',
    category: 'Cache',
    type: 'string',
    default: '180d',
    validate: (v: string) => /^\s*\d+(\.\d+)?\s*(s|sec|m|min|h|hr|d|w|y)?\s*$/i.test(v),
  },
  {
    key: 'SETTLE_SERIES',
    envVar: 'SETTLE_SERIES',
    label: 'Series Settle Window',
    description: 'Minimum age since last air/end before a series/anime is disk-eligible (e.g. 90d)',
    category: 'Cache',
    type: 'string',
    default: '90d',
    validate: (v: string) => /^\s*\d+(\.\d+)?\s*(s|sec|m|min|h|hr|d|w|y)?\s*$/i.test(v),
  },
  {
    key: 'FROZEN_AGE',
    envVar: 'FROZEN_AGE',
    label: 'Frozen Age Threshold',
    description: 'Age past which a stable entry is treated as frozen (longer TTL) (e.g. 2y)',
    category: 'Cache',
    type: 'string',
    default: '2y',
    validate: (v: string) => /^\s*\d+(\.\d+)?\s*(s|sec|m|min|h|hr|d|w|y)?\s*$/i.test(v),
  },
  {
    key: 'COLD_STORE_INACTIVE_DAYS',
    envVar: 'COLD_STORE_INACTIVE_DAYS',
    label: 'Cold Store Inactive Days',
    description: 'Drop cold-store rows untouched for this many days',
    category: 'Cache',
    type: 'number',
    default: 30,
    min: 1,
  },
  {
    key: 'IMAGE_WARM_QUEUE',
    envVar: 'IMAGE_WARM_QUEUE',
    label: 'Image Warm Queue',
    description: 'Warm images through one bounded background queue instead of per-catalog chains',
    category: 'Comprehensive Warming',
    type: 'boolean',
    default: true,
  },
  {
    key: 'IMAGE_WARM_QUEUE_MAX',
    envVar: 'IMAGE_WARM_QUEUE_MAX',
    label: 'Image Warm Queue Depth',
    description: 'Maximum images waiting to be warmed; beyond this they are dropped and filled on demand instead',
    category: 'Comprehensive Warming',
    type: 'number',
    default: 50000,
    min: 1,
  },
  {
    key: 'IMAGE_WARM_CONCURRENCY_MIN',
    envVar: 'IMAGE_WARM_CONCURRENCY_MIN',
    label: 'Image Warm Concurrency (min)',
    description: 'Lower bound the adaptive image warmer will not throttle below',
    category: 'Comprehensive Warming',
    type: 'number',
    default: 4,
    min: 1,
  },
  {
    key: 'IMAGE_WARM_CONCURRENCY_MAX',
    envVar: 'IMAGE_WARM_CONCURRENCY_MAX',
    label: 'Image Warm Concurrency (max)',
    description: 'Upper bound the adaptive image warmer will ramp up to when the event loop has headroom',
    category: 'Comprehensive Warming',
    type: 'number',
    default: 48,
    min: 1,
  },
  {
    key: 'IMAGE_WARM_TARGET_LAG_MS',
    envVar: 'IMAGE_WARM_TARGET_LAG_MS',
    label: 'Image Warm Target Lag (ms)',
    description: 'Event-loop lag the image warmer aims to stay under; it backs off above this and speeds up below it',
    category: 'Comprehensive Warming',
    type: 'number',
    default: 20,
    min: 1,
  },
  {
    key: 'IMAGE_WARM_PROXY_BASE',
    envVar: 'IMAGE_WARM_PROXY_BASE',
    label: 'Image Warm Proxy Base',
    description: 'Where the warmer fetches rendered posters from. Leave empty to use loopback on this instance, which keeps a warm run off the public network. Set it only if the instance cannot reach its own port.',
    category: 'Comprehensive Warming',
    type: 'string',
    default: '',
  },
  {
    key: 'COLD_STORE_STATS_TTL',
    envVar: 'COLD_STORE_STATS_TTL',
    label: 'Cold Store Stats TTL',
    description: 'How long the dashboard cold-store size figures are reused before recounting (0 disables)',
    category: 'Cache',
    type: 'string',
    default: '30s',
    validate: (v: string) => /^\s*\d+(\.\d+)?\s*(s|sec|m|min|h|hr|d|w|y)?\s*$/i.test(v),
  },
];

// Rules: when a setting has a certain value, other settings become disabled.
// Evaluated server-side so the frontend gets a flat disabled/disabledReason per setting.
export interface ConditionalRule {
  when: { key: string; eq: string };
  disable: { keys?: string[]; categories?: string[] };
  reason: string;
}

export const CONDITIONAL_RULES: ConditionalRule[] = [
  {
    when: { key: 'CACHE_WARMUP_MODE', eq: 'comprehensive' },
    disable: { categories: ['MAL Warming'], keys: ['TMDB_POPULAR_WARMING_ENABLED'] },
    reason: 'Disabled in comprehensive mode',
  },
  {
    when: { key: 'CACHE_WARMUP_MODE', eq: 'essential' },
    disable: {
      keys: [
        'CACHE_WARMUP_UUIDS', 'CATALOG_WARMUP_INTERVAL_HOURS', 'CATALOG_WARMUP_INITIAL_DELAY_SECONDS',
        'CATALOG_WARMUP_MAX_PAGES_PER_CATALOG', 'CATALOG_WARMUP_TASK_DELAY_MS',
        'CATALOG_WARMUP_RESUME_ON_RESTART', 'CATALOG_WARMUP_QUIET_HOURS_ENABLED',
        'CATALOG_WARMUP_QUIET_HOURS', 'CATALOG_WARMUP_LOG_LEVEL',
        'CATALOG_WARMUP_AUTO_ON_EPOCH_CHANGE', 'POSTER_WARMUP_URL',
      ],
    },
    reason: 'Warmup mode is set to essential',
  },
  {
    when: { key: 'ENABLE_CACHE_WARMING', eq: 'false' },
    disable: {
      keys: [
        'CACHE_WARMING_INTERVAL', 'CACHE_WARM_INTERVAL_HOURS',
        'CACHE_WARM_LANGUAGE', 'TMDB_POPULAR_WARMING_ENABLED',
      ],
    },
    reason: 'Essential cache warming is disabled',
  },
  {
    when: { key: 'ENABLE_BUILTIN_POSTER_CACHE', eq: 'false' },
    disable: {
      keys: [
        'POSTER_CACHE_BACKGROUNDS', 'POSTER_CACHE_LANDSCAPE_POSTERS',
        'POSTER_CACHE_LOGOS', 'POSTER_CACHE_THUMBNAILS',
        'POSTER_CACHE_PROCESSED_IMAGES', 'POSTER_CACHE_MAX_SIZE',
        'POSTER_CACHE_TTL_DAYS',
        'POSTER_CACHE_INFER_TTL',
        'POSTER_CACHE_INACTIVE_DAYS', 'POSTER_CACHE_MAX_OBJECT_BYTES',
        'POSTER_CACHE_DIR', 'POSTER_CACHE_IMPORT_NGINX_DIR',
        'POSTER_CACHE_FETCH_CONCURRENCY', 'POSTER_CACHE_STREAM_THRESHOLD',
        'POSTER_CACHE_LOG_REQUESTS', 'POSTER_CACHE_MEMORY_SIZE',
      ],
    },
    reason: 'The built-in image cache is disabled',
  },
  {
    when: { key: 'META_COLD_STORE_ENABLED', eq: 'false' },
    disable: {
      keys: [
        'META_COLD_STORE_PATH', 'META_COLD_STORE_MAX_BYTES',
        'META_COLD_STORE_COMPRESSION',
        'COLD_TTL_FROZEN', 'COLD_TTL_STABLE',
        'SETTLE_MOVIE', 'SETTLE_SERIES', 'FROZEN_AGE',
        'COLD_STORE_INACTIVE_DAYS', 'COLD_STORE_STATS_TTL',
      ],
    },
    reason: 'The meta cold store is disabled',
  },
];

const registryMap = new Map<string, SettingDefinition>();
for (const def of SETTINGS_REGISTRY) {
  registryMap.set(def.key, def);
}

export function getSettingDefinition(key: string): SettingDefinition | undefined {
  return registryMap.get(key);
}

export function getSettingsByCategory(): Map<string, SettingDefinition[]> {
  const categories = new Map<string, SettingDefinition[]>();
  for (const def of SETTINGS_REGISTRY) {
    const list = categories.get(def.category) || [];
    list.push(def);
    categories.set(def.category, list);
  }
  return categories;
}
